Compatibility upgraded to HWI 2.0.2 binary
bitcoindevkit/rust-hwi pull request #9
Opened 2022-03-06 09:51 UTC by wszdexdrf

Updated flags and commands to better match the current version of the HWI binary.
Some tests are changed to better suit the changed address types. Kindly verify the tests if they are up to mark. I changed the Derivation Paths to comply with BIP44 which was supported by my hardware wallet.

2022-03-06 09:52 UTC, wszdexdrf commented
I have no idea why taproot checksum fails.

2022-03-06 17:43 UTC, wszdexdrf commented
Fixes #3. Fixes #4. Fixes #5.

2022-03-06 17:46 UTC, wszdexdrf commented
Added commits to fix #4, fix #3, fix #5.

2022-05-07 21:12 UTC, danielabrozzoni requested changes
It's looking really good! There are some nits here and there. 
At the moment on my trezor simulator `test_sign_message` is failing, but it's probably not your fault. I'm looking into it right now!
Also, please rename dda3a5494aee6a3898f26b316443cd0a924093e6, b31878360e4d452db8de02e9f1393d61f86c2813, a02d819f29c798005ddcdc2bc3c086cc4711afa3: put as a title of the commit what the commit is doing, and as a comment which issue it's fixing. This way we know what each commit is doing even before opening github.

2022-05-08 04:58 UTC, wszdexdrf commented
Just a sec. I will create a new PR in a moment. I think I messed something up. I noted your comments and am working on them. Sorry.

2022-05-08 04:58 UTC, closed without merging

2022-05-08 06:31 UTC, wszdexdrf commented on src/types.rs
> +    #[serde(deserialize_with="deserialize_psbt")]
Can it work even when the string is base64 encoded? I tried and couldn't get it to work so I just decoded the base64 and then deserialized with serde and that works...

2022-05-08 06:39 UTC, wszdexdrf commented on src/lib.rs
> +    // TODO: Taproot Checksum fails
Yeah, about that. The docs say that it isn't supported, hwi executable actually works with taproot.
![image](https://user-images.githubusercontent.com/81520912/167284985-3282c9e9-052e-4472-9890-4cc6e036446a.png)

2022-05-08 10:08 UTC, danielabrozzoni commented
You don't need to create a new PR, force pushing on the branch you're using will update the one already open.
It's better if we work only on one PR, this way all the discussion remain in one place :)

2022-05-08 10:40 UTC, danielabrozzoni commented on src/lib.rs
> +    // TODO: Taproot Checksum fails
That's weird... I'm on hwi 2.0.2 and `displayaddress -h` doesn't list `tap` 🤷🏻‍♀️ 

```
❯ hwi displayaddress -h
usage: hwi displayaddress [-h] (--desc DESC | --path PATH) [--addr-type {legacy,wit,sh_wit}]

optional arguments:
  -h, --help            show this help message and exit
  --desc DESC           Output Descriptor. E.g. wpkh([00000000/84h/0h/0h]xpub.../0/0), where
                        00000000 must match --fingerprint and xpub can be obtained with
                        getxpub. See doc/descriptors.md in Bitcoin Core (default: None)
  --path PATH           The BIP 32 derivation path of the key embedded in the address,
                        default follows BIP43 convention, e.g. ``m/84h/0h/0h/1/*`` (default:
                        None)
  --addr-type {legacy,wit,sh_wit}
                        The address type to display (default: wit)
{"error": "Help text requested", "code": -17}
```

```
❯ hwi --version
hwi 2.0.2
```

2022-05-08 10:51 UTC, wszdexdrf commented
Yeah. I realise that now. I will keep that in mind. Thanks.

2022-05-08 10:55 UTC, wszdexdrf commented
Only the first few bug fixes are on master currently. For the next portion of incorporating PyO3 I will use a separate branch. I was doing multiple reverts, rebases and resets (I got confused between them) so I worried it would make the PR too complicated so I closed this one and opened a new, clean one.